name: Update artists.json

on:
  push:
    paths:
      - 'a/**/config.json'

jobs:
  update-portfolio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Update Portfolio
        run: node .github/workflows/update-artists.js
